🔀 :: (#7) Flow&DI 추가
Yuseong-AllowancePayments/Yuseong_AllowancePayments_iPadOS pull request #8
Opened 2023-10-09 05:34 UTC by juyeong525

2023-10-09 05:53 UTC, DSMInhyeKang requested changes

2023-10-09 05:53 UTC, DSMInhyeKang commented on Projects/App/Sources/App/AppDI.swift
> +
공백 남겨둔 이유가 있나요

2023-10-09 05:53 UTC, DSMInhyeKang commented on Projects/App/Sources/App/Flow/AppFlow.swift
> +
여기랑 34번도

2023-10-09 05:53 UTC, DSMInhyeKang commented on Projects/App/Sources/App/Flow/AppStepper.swift
> +
여기랑 8번

2023-10-09 05:53 UTC, DSMInhyeKang commented on Projects/App/Sources/App/Flow/SelectTypeFlow.swift
> +    private let rootViewController = UINavigationController()
여기는 공백 안 줬나요

2023-10-09 05:53 UTC, DSMInhyeKang commented on Projects/App/Sources/App/Flow/YuseongAllowanceStep.swift
> +
여기 공백은 왜 들어가나요

2023-10-09 06:04 UTC, DSMInhyeKang requested changes

2023-10-09 06:04 UTC, DSMInhyeKang commented on Projects/App/Sources/App/SceneDelegate.swift
> +        window?.backgroundColor = .systemBackground
라이트 다크 설정하려면 BaseVC에 뷰 백 컬러 코드 지워야 ㅎㅐ요

2023-10-09 06:04 UTC, DSMInhyeKang commented on Projects/App/Sources/App/SceneDelegate.swift
> -        let mainViewController = BaseNC(rootViewController: SelectTypeViewController())
BaseNC 파일 삭제해도 되지 않을까요

2023-10-09 06:06 UTC, DSMInhyeKang requested changes

2023-10-09 06:06 UTC, DSMInhyeKang commented on Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewController.swift
> -                nextVC.titleLabel.text = "\(self.selectedType.value) 지급 신청서 작성"
여기 빠지면 텍스트 필드 있는 쪽에 버튼만 있고 뭐 안 나와요

2023-10-09 06:07 UTC, juyeong525 commented on Projects/App/Sources/App/SceneDelegate.swift
> +        window?.backgroundColor = .systemBackground
니가 넣으셨어요

2023-10-09 06:07 UTC, juyeong525 commented on Projects/App/Sources/App/SceneDelegate.swift
> -        let mainViewController = BaseNC(rootViewController: SelectTypeViewController())
너가 넣었어요

2023-10-09 06:07 UTC, juyeong525 commented on Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewController.swift
> -                nextVC.titleLabel.text = "\(self.selectedType.value) 지급 신청서 작성"
니가 한거잖아요

2023-10-09 12:37 UTC, DSMInhyeKang commented on Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewController.swift
> -                nextVC.titleLabel.text = "\(self.selectedType.value) 지급 신청서 작성"
아니 님이 bind에 step만 들어가게 바꾸셨잖아요

2023-10-10 06:18 UTC, merged

2023-10-10 06:22 UTC, DSMInhyeKang reviewed
굿굿 주영 최고야 정말 잘했어